[tool.poetry]
name = "topyn"
version = "0.1.0"
description = ""
authors = ["leandro.leites <leandro.leites@flixbus.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.7"
flake8-bugbear = "^19.8"
flake8-print = "^3.1"
flake8-comprehensions = "^3.1"
black = "19.10b0"
mypy = "^0.740.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.8"

[tool.poetry.scripts]
topyn = 'topyn:console.run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

